# Generated by Django 2.2.5 on 2019-09-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketBooking',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='Park_name',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='country',
        ),
    ]
