# Generated by Django 2.2.5 on 2019-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='online', editable=False, max_length=7),
        ),
    ]
