# Generated by Django 2.2.5 on 2019-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20190907_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'online')], max_length=10),
        ),
    ]
