# Generated by Django 2.2.5 on 2019-09-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20190907_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], max_length=10),
        ),
    ]
