# Generated by Django 2.2.5 on 2019-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20190907_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'online')], max_length=10),
        ),
    ]
