# Generated by Django 2.2.5 on 2019-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touroperator', '0002_auto_20190906_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Ticket_id',
            field=models.PositiveIntegerField(default='1741'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='9966'),
        ),
    ]
