# Generated by Django 2.2.5 on 2019-09-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touroperator', '0010_auto_20190907_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Ticket_id',
            field=models.PositiveIntegerField(default='4504'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='9963'),
        ),
    ]
