# Generated by Django 2.2.5 on 2019-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touroperator', '0012_auto_20190909_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Ticket_id',
            field=models.PositiveIntegerField(default='2889'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Employ_id',
            field=models.PositiveIntegerField(default='5177'),
        ),
    ]
